### ISSUE TITLE
Instructor Guide's Live Demo section describes Consul demo instead of Vault demo

### ISSUE THREAD

**Issue by robertpeteuil** [hashicorp/field-workshops-vault#18]
The [Live Demo](https://github.com/hashicorp/field-workshops-vault/blob/master/instructor-guides/INSTRUCTOR_GUIDE.md#the-live-demo) section in the Instructor Guide appears to be describing a Consul demo.

**Comment by rberlind** [comment]
Closing this since I created a separate Instructor guide for Vault workshop
