### ISSUE TITLE
Web UI doesn't show error messages when user doesn't have permission

### ISSUE THREAD

**Issue by jacobm3** [hashicorp/field-workshops-vault#34]
The Vault web UI is not giving any user feedback when a userpass user tries to save a KV entry at a path for which they don't have permission. The save button just doesn't do anything.

**Comment by rberlind** [comment]
@jacobm3 :  I don't think that should be an issue listed in this project.  Instead, you should file an issue under https://github.com/hashicorp/vault/issues.  I'm going to close this.
